# Generated by Django 3.1 on 2020-08-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'новый участник (первый месяц)'), ('P', 'регулярный участник'),
                                                   ('B', 'заблокированный'), ('E', 'наш сотрудник'),
                                                   ('V', 'VIP (особые условия, например, участие без оплаты)')],
                                          default='N', max_length=1,
                                          verbose_name='Тип участника: P - регулярный участник; B - заблокированный; E - наш сотрудник; V - VIP (особые условия, например, участие без оплаты)')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram id')),
            ],
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статью', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
