# Generated by Django 3.1 on 2020-08-15 14:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0002_auto_20200815_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='comment',
            field=models.CharField(max_length=4000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='participant',
            name='date_until_date',
            field=models.DateField(null=True, verbose_name='Дата выдачи отсрочки'),
        ),
        migrations.AddField(
            model_name='participant',
            name='deadline',
            field=models.DateField(null=True, verbose_name='Дата следующей оплаты'),
        ),
        migrations.AddField(
            model_name='participant',
            name='email',
            field=models.CharField(db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='participant',
            name='fio',
            field=models.CharField(db_index=True, max_length=4000, null=True, verbose_name='Фамилия и Имя по русски'),
        ),
        migrations.AddField(
            model_name='participant',
            name='fio_eng',
            field=models.CharField(db_index=True, max_length=4000, null=True,
                                   verbose_name='Фамилия и Имя по английски'),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=2000, null=True, verbose_name='Имя по русски'),
        ),
        migrations.AddField(
            model_name='participant',
            name='first_name_eng',
            field=models.CharField(max_length=2000, null=True, verbose_name='Имя по английски'),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=2000, null=True, verbose_name='Фамилия по русски'),
        ),
        migrations.AddField(
            model_name='participant',
            name='last_name_eng',
            field=models.CharField(max_length=2000, null=True, verbose_name='Фамилия по английски'),
        ),
        migrations.AddField(
            model_name='participant',
            name='login',
            field=models.CharField(max_length=2000, null=True,
                                   verbose_name='Логин пользователя в домене @givinschool.org, соответствует почте'),
        ),
        migrations.AddField(
            model_name='participant',
            name='number_of_days',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Количество оплаченных дней'),
        ),
        migrations.AddField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=30, null=True, verbose_name='Пароль участника'),
        ),
        migrations.AddField(
            model_name='participant',
            name='payment_date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AddField(
            model_name='participant',
            name='telegram',
            field=models.CharField(db_index=True, max_length=32, null=True, verbose_name='Telegram name'),
        ),
        migrations.AddField(
            model_name='participant',
            name='time_begin',
            field=models.DateTimeField(default=datetime.date.today, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='participant',
            name='time_end',
            field=models.DateTimeField(null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AddField(
            model_name='participant',
            name='until_date',
            field=models.DateField(null=True, verbose_name='Дата до которой отсрочен платёж'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram_id',
            field=models.BigIntegerField(null=True, verbose_name='Telegram id'),
        ),
    ]
