# Generated by Django 3.1 on 2020-08-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0003_auto_20200815_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fio',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Фамилия и Имя по русски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя по русски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия по русски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_begin',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
