# Generated by Django 3.1 on 2020-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0004_auto_20200820_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='fio_eng',
            field=models.CharField(db_index=True, max_length=500, null=True, verbose_name='Фамилия и Имя по английски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя по английски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name_eng',
            field=models.CharField(max_length=255, null=True, verbose_name='Фамилия по английски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='login',
            field=models.CharField(max_length=32, null=True,
                                   verbose_name='Логин пользователя в домене @givinschool.org, соответствует почте'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(max_length=32, null=True, verbose_name='Пароль участника'),
        ),
    ]
