# Generated by Django 3.1 on 2020-08-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gtp_index', '0005_auto_20200820_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участника', 'verbose_name_plural': 'Участников'},
        ),
    ]
