# Generated by Django 3.1 on 2020-08-20 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0006_auto_20200820_1448'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""ALTER TABLE gtp_index_participant ALTER COLUMN time_begin SET DEFAULT CURRENT_TIMESTAMP""",
            reverse_sql="ALTER TABLE gtp_index_participant ALTER COLUMN time_begin DROP DEFAULT",
        ),

    ]
