# Generated by Django 3.1 on 2020-09-11 13:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0008_auto_20200829_1804'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
