# Generated by Django 3.1 on 2020-09-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0009_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='login',
            field=models.CharField(max_length=100, null=True,
                                   verbose_name='Логин пользователя в домене @givinschool.org, соответствует почте'),
        ),
    ]
