# Generated by Django 3.1 on 2020-10-21 12:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('gtp_index', '0010_auto_20200911_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='comment',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='date_until_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи отсрочки'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей оплаты'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='email',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fio',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True,
                                   verbose_name='Фамилия и Имя по русски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='fio_eng',
            field=models.CharField(blank=True, db_index=True, max_length=500, null=True,
                                   verbose_name='Фамилия и Имя по английски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя по русски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='first_name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя по английски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия по русски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='last_name_eng',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия по английски'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='login',
            field=models.CharField(blank=True, max_length=100, null=True,
                                   verbose_name='Логин пользователя в домене @givinschool.org, соответствует почте'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='number_of_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество оплаченных дней'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Пароль участника'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='payment_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, verbose_name='Telegram name'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='time_end',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата блокировки'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='type',
            field=models.CharField(
                choices=[('N', 'новый участник (первый месяц)'), ('P', 'регулярный участник'), ('B', 'заблокированный'),
                         ('E', 'наш сотрудник'), ('V', 'VIP (особые условия, например, участие без оплаты)')],
                default='N', max_length=1,
                verbose_name='Тип участника: '
                             'N - новый участник (первый месяц); '
                             'P - регулярный участник; '
                             'B - заблокированный; '
                             'E - наш сотрудник; '
                             'V - VIP (особые условия, например, участие без оплаты)'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='until_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата до которой отсрочен платёж'),
        ),
    ]
