# Generated by Django 3.1 on 2020-10-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""ALTER TABLE sf_participant ALTER COLUMN time_begin SET DEFAULT CURRENT_TIMESTAMP""",
            reverse_sql="ALTER TABLE sf_participant ALTER COLUMN time_begin DROP DEFAULT",
        ),
    ]
