# Generated by Django 3.1 on 2020-10-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sf', '0002_alter_column_time_begin'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""ALTER TABLE sf_participant ALTER COLUMN payment_date SET DEFAULT CURRENT_DATE""",
            reverse_sql="ALTER TABLE sf_participant ALTER COLUMN payment_date DROP DEFAULT",
        ),
    ]
